# Base Image
FROM python:3.6.5-alpine

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Add and install requirements
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# Add app
COPY . /usr/src/app

# Run server
CMD python manage.py run -h 0.0.0.0
